version: "3"

services:
  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - local
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.2
    command: sh -c "redis-server --requirepass password123"
    networks:
      - local
    ports:
      - 6379:6379

networks:
  local:
    driver: bridge
